
package com.newmusic.webservice.resource.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Thu Apr 25 23:45:55 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "AddArtist", namespace = "http://www.com.newmusic.webservice.resource")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddArtist", namespace = "http://www.com.newmusic.webservice.resource")

public class AddArtist {

    @XmlElement(name = "Artist")
    private com.newmusic.webservice.data.Artist Artist;

    public com.newmusic.webservice.data.Artist getArtist() {
        return this.Artist;
    }

    public void setArtist(com.newmusic.webservice.data.Artist newArtist)  {
        this.Artist = newArtist;
    }

}

