
package com.newmusic.webservice.resource.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Thu Apr 25 23:45:55 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "GetEventResponse", namespace = "http://www.com.newmusic.webservice.resource")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetEventResponse", namespace = "http://www.com.newmusic.webservice.resource")

public class GetEventResponse {

    @XmlElement(name = "Event")
    private com.newmusic.webservice.data.MusicEvent Event;

    public com.newmusic.webservice.data.MusicEvent getEvent() {
        return this.Event;
    }

    public void setEvent(com.newmusic.webservice.data.MusicEvent newEvent)  {
        this.Event = newEvent;
    }

}

