
package com.newmusic.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.newmusic.webservice.client.Artist;
import com.newmusic.webservice.client.MusicEvent;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-26T00:33:33.983+02:00
 * Generated source version: 3.5.7
 *
 */
public final class MusicResourceWS_MusicResourceWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.com.newmusic.webservice.resource", "MusicResourceWSService");

    private MusicResourceWS_MusicResourceWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MusicResourceWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MusicResourceWSService ss = new MusicResourceWSService(wsdlURL, SERVICE_NAME);
        MusicResourceWS port = ss.getMusicResourceWSPort();
        
        System.out.println("Adding Taylor Swift...");
        Artist _addArtist_artist = new Artist();
        java.lang.Integer _addArtist__return = port.addArtist(_addArtist_artist);
        System.out.println("addArtist.result=" + _addArtist__return);
        
        System.out.println("\nInvoking getArtist...");
        int _getArtist_artistId = _addArtist__return;
        Artist _getArtist__return = port.getArtist(_getArtist_artistId);
        System.out.println("getArtist.result=" + _getArtist__return);
        
        System.out.println("\nInvoking addUpcomingEvent...");
        int _addUpcomingEvent_artistId = _addArtist__return;
        MusicEvent _addUpcomingEvent_event = new MusicEvent();
        java.lang.Integer _addUpcomingEvent__return = port.addUpcomingEvent(_addUpcomingEvent_artistId, _addUpcomingEvent_event);
        System.out.println("addUpcomingEvent.result=" + _addUpcomingEvent__return);
        
        System.out.println("\nInvoking getEvent...");
        int _getEvent_artistId = _addArtist__return;
        int _getEvent_eventId = _addUpcomingEvent__return;
        MusicEvent _getEvent__return = port.getEvent(_getEvent_artistId, _getEvent_eventId);
        System.out.println("getEvent.result=" + _getEvent__return.getEventId());
/*
        System.out.println("\nInvoking deleteArtist...");
        int _deleteArtist_artistId = _addArtist__return;
        boolean _deleteArtist__return = port.deleteArtist(_deleteArtist_artistId);
        System.out.println("deleteArtist.result=" + _deleteArtist__return);
*/
        /*
        {
        System.out.println("Invoking addUpcomingEvent...");
        int _addUpcomingEvent_artistId = 802420856;
        com.newmusic.webservice.client.MusicEvent _addUpcomingEvent_event = new com.newmusic.webservice.client.MusicEvent();
        _addUpcomingEvent_event.setDisambiguation("Disambiguation1182028026");
        _addUpcomingEvent_event.setEventId(2030346908);
        _addUpcomingEvent_event.setEventName("EventName1742532421");
        _addUpcomingEvent_event.setLocation("Location-168520103");
        com.newmusic.webservice.client.Artist _addUpcomingEvent_eventPerformer = new com.newmusic.webservice.client.Artist();
        _addUpcomingEvent_eventPerformer.setAlias("Alias-1118750159");
        _addUpcomingEvent_eventPerformer.setCountry("Country663564882");
        _addUpcomingEvent_eventPerformer.setDead(true);
        _addUpcomingEvent_eventPerformer.setDisambiguation("Disambiguation2143063720");
        java.util.List<com.newmusic.webservice.client.MusicEvent> _addUpcomingEvent_eventPerformerEvents = new java.util.ArrayList<com.newmusic.webservice.client.MusicEvent>();
        com.newmusic.webservice.client.MusicEvent _addUpcomingEvent_eventPerformerEventsVal1 = new com.newmusic.webservice.client.MusicEvent();
        _addUpcomingEvent_eventPerformerEventsVal1.setDisambiguation("Disambiguation840292423");
        _addUpcomingEvent_eventPerformerEventsVal1.setEventId(-140951113);
        _addUpcomingEvent_eventPerformerEventsVal1.setEventName("EventName160940438");
        _addUpcomingEvent_eventPerformerEventsVal1.setLocation("Location-1910927628");
        com.newmusic.webservice.client.Artist _addUpcomingEvent_eventPerformerEventsVal1Performer = new com.newmusic.webservice.client.Artist();
        _addUpcomingEvent_eventPerformerEventsVal1Performer.setAlias("Alias-176683746");
        _addUpcomingEvent_eventPerformerEventsVal1Performer.setCountry("Country1254495233");
        _addUpcomingEvent_eventPerformerEventsVal1Performer.setDead(true);
        _addUpcomingEvent_eventPerformerEventsVal1Performer.setDisambiguation("Disambiguation1105315956");
        java.util.List<com.newmusic.webservice.client.MusicEvent> _addUpcomingEvent_eventPerformerEventsVal1PerformerEvents = new java.util.ArrayList<com.newmusic.webservice.client.MusicEvent>();
        _addUpcomingEvent_eventPerformerEventsVal1Performer.getEvents().addAll(_addUpcomingEvent_eventPerformerEventsVal1PerformerEvents);
        _addUpcomingEvent_eventPerformerEventsVal1Performer.setFirstName("FirstName-1693330758");
        _addUpcomingEvent_eventPerformerEventsVal1Performer.setGender("Gender-1706328343");
        _addUpcomingEvent_eventPerformerEventsVal1Performer.setLastName("LastName1327901943");
        _addUpcomingEvent_eventPerformerEventsVal1.setPerformer(_addUpcomingEvent_eventPerformerEventsVal1Performer);
        _addUpcomingEvent_eventPerformerEventsVal1.setScore(-102589876);
        _addUpcomingEvent_eventPerformerEventsVal1.setType("Type-1589042632");
        _addUpcomingEvent_eventPerformerEvents.add(_addUpcomingEvent_eventPerformerEventsVal1);
        _addUpcomingEvent_eventPerformer.getEvents().addAll(_addUpcomingEvent_eventPerformerEvents);
        _addUpcomingEvent_eventPerformer.setFirstName("FirstName-953784179");
        _addUpcomingEvent_eventPerformer.setGender("Gender-1328505374");
        _addUpcomingEvent_eventPerformer.setLastName("LastName1656298511");
        _addUpcomingEvent_event.setPerformer(_addUpcomingEvent_eventPerformer);
        _addUpcomingEvent_event.setScore(-425380353);
        _addUpcomingEvent_event.setType("Type-791494762");
        java.lang.Integer _addUpcomingEvent__return = port.addUpcomingEvent(_addUpcomingEvent_artistId, _addUpcomingEvent_event);
        System.out.println("addUpcomingEvent.result=" + _addUpcomingEvent__return);


        }
        {
        System.out.println("Invoking getEvent...");
        int _getEvent_artistId = 949853860;
        int _getEvent_eventId = 172641413;
        com.newmusic.webservice.client.MusicEvent _getEvent__return = port.getEvent(_getEvent_artistId, _getEvent_eventId);
        System.out.println("getEvent.result=" + _getEvent__return);


        }
        {
        System.out.println("Invoking deleteArtist...");
        int _deleteArtist_artistId = -2102480076;
        boolean _deleteArtist__return = port.deleteArtist(_deleteArtist_artistId);
        System.out.println("deleteArtist.result=" + _deleteArtist__return);


        }
        {
        System.out.println("Invoking getEvents...");
        int _getEvents_artistId = 1558860189;
        com.newmusic.webservice.client.Artist _getEvents__return = port.getEvents(_getEvents_artistId);
        System.out.println("getEvents.result=" + _getEvents__return);


        }
        {
        System.out.println("Invoking deleteEvent...");
        int _deleteEvent_artistId = 1544023181;
        int _deleteEvent_eventId = -372709203;
        boolean _deleteEvent__return = port.deleteEvent(_deleteEvent_artistId, _deleteEvent_eventId);
        System.out.println("deleteEvent.result=" + _deleteEvent__return);


        }
        {
        System.out.println("Invoking getArtist...");
        int _getArtist_artistId = 2034878067;
        com.newmusic.webservice.client.Artist _getArtist__return = port.getArtist(_getArtist_artistId);
        System.out.println("getArtist.result=" + _getArtist__return);


        }
        {
        System.out.println("Invoking addArtist...");
        com.newmusic.webservice.client.Artist _addArtist_artist = new com.newmusic.webservice.client.Artist();
        _addArtist_artist.setAlias("Alias-9428022");
        _addArtist_artist.setCountry("Country-375958609");
        _addArtist_artist.setDead(true);
        _addArtist_artist.setDisambiguation("Disambiguation306274235");
        java.util.List<com.newmusic.webservice.client.MusicEvent> _addArtist_artistEvents = new java.util.ArrayList<com.newmusic.webservice.client.MusicEvent>();
        com.newmusic.webservice.client.MusicEvent _addArtist_artistEventsVal1 = new com.newmusic.webservice.client.MusicEvent();
        _addArtist_artistEventsVal1.setDisambiguation("Disambiguation1978020286");
        _addArtist_artistEventsVal1.setEventId(1825820149);
        _addArtist_artistEventsVal1.setEventName("EventName101913351");
        _addArtist_artistEventsVal1.setLocation("Location246790569");
        com.newmusic.webservice.client.Artist _addArtist_artistEventsVal1Performer = new com.newmusic.webservice.client.Artist();
        _addArtist_artistEventsVal1Performer.setAlias("Alias1892005554");
        _addArtist_artistEventsVal1Performer.setCountry("Country-1386021000");
        _addArtist_artistEventsVal1Performer.setDead(false);
        _addArtist_artistEventsVal1Performer.setDisambiguation("Disambiguation-1567645720");
        java.util.List<com.newmusic.webservice.client.MusicEvent> _addArtist_artistEventsVal1PerformerEvents = new java.util.ArrayList<com.newmusic.webservice.client.MusicEvent>();
        _addArtist_artistEventsVal1Performer.getEvents().addAll(_addArtist_artistEventsVal1PerformerEvents);
        _addArtist_artistEventsVal1Performer.setFirstName("FirstName-439327520");
        _addArtist_artistEventsVal1Performer.setGender("Gender2073076757");
        _addArtist_artistEventsVal1Performer.setLastName("LastName-41504292");
        _addArtist_artistEventsVal1.setPerformer(_addArtist_artistEventsVal1Performer);
        _addArtist_artistEventsVal1.setScore(-734189337);
        _addArtist_artistEventsVal1.setType("Type-1405931743");
        _addArtist_artistEvents.add(_addArtist_artistEventsVal1);
        _addArtist_artist.getEvents().addAll(_addArtist_artistEvents);
        _addArtist_artist.setFirstName("FirstName-2022194630");
        _addArtist_artist.setGender("Gender596762571");
        _addArtist_artist.setLastName("LastName2014566093");
        java.lang.Integer _addArtist__return = port.addArtist(_addArtist_artist);
        System.out.println("addArtist.result=" + _addArtist__return);


        }*/

        System.exit(0);
    }

}
