package com.newmusic.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-26T00:33:34.157+02:00
 * Generated source version: 3.5.7
 *
 */
@WebService(targetNamespace = "http://www.com.newmusic.webservice.resource", name = "MusicResourceWS")
@XmlSeeAlso({ObjectFactory.class})
public interface MusicResourceWS {

    @WebMethod(operationName = "AddUpcomingEvent")
    @RequestWrapper(localName = "AddUpcomingEvent", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.AddUpcomingEvent")
    @ResponseWrapper(localName = "AddUpcomingEventResponse", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.AddUpcomingEventResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public java.lang.Integer addUpcomingEvent(

        @WebParam(name = "ArtistId", targetNamespace = "")
        int artistId,
        @WebParam(name = "Event", targetNamespace = "")
        com.newmusic.webservice.client.MusicEvent event
    );

    @WebMethod(operationName = "GetEvent")
    @RequestWrapper(localName = "GetEvent", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.GetEvent")
    @ResponseWrapper(localName = "GetEventResponse", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.GetEventResponse")
    @WebResult(name = "Event", targetNamespace = "")
    public com.newmusic.webservice.client.MusicEvent getEvent(

        @WebParam(name = "ArtistId", targetNamespace = "")
        int artistId,
        @WebParam(name = "EventId", targetNamespace = "")
        int eventId
    );

    @WebMethod(operationName = "DeleteArtist")
    @RequestWrapper(localName = "DeleteArtist", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.DeleteArtist")
    @ResponseWrapper(localName = "DeleteArtistResponse", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.DeleteArtistResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public boolean deleteArtist(

        @WebParam(name = "ArtistId", targetNamespace = "")
        int artistId
    );

    @WebMethod(operationName = "GetEvents")
    @RequestWrapper(localName = "GetEvents", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.GetEvents")
    @ResponseWrapper(localName = "GetEventsResponse", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.GetEventsResponse")
    @WebResult(name = "Events", targetNamespace = "")
    public com.newmusic.webservice.client.Artist getEvents(

        @WebParam(name = "ArtistId", targetNamespace = "")
        int artistId
    );

    @WebMethod(operationName = "DeleteEvent")
    @RequestWrapper(localName = "DeleteEvent", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.DeleteEvent")
    @ResponseWrapper(localName = "DeleteEventResponse", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.DeleteEventResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public boolean deleteEvent(

        @WebParam(name = "ArtistId", targetNamespace = "")
        int artistId,
        @WebParam(name = "EventId", targetNamespace = "")
        int eventId
    );

    @WebMethod(operationName = "GetArtist")
    @RequestWrapper(localName = "GetArtist", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.GetArtist")
    @ResponseWrapper(localName = "GetArtistResponse", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.GetArtistResponse")
    @WebResult(name = "Artist", targetNamespace = "")
    public com.newmusic.webservice.client.Artist getArtist(

        @WebParam(name = "ArtistId", targetNamespace = "")
        int artistId
    );

    @WebMethod(operationName = "AddArtist")
    @RequestWrapper(localName = "AddArtist", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.AddArtist")
    @ResponseWrapper(localName = "AddArtistResponse", targetNamespace = "http://www.com.newmusic.webservice.resource", className = "com.newmusic.webservice.client.AddArtistResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public java.lang.Integer addArtist(

        @WebParam(name = "Artist", targetNamespace = "")
        com.newmusic.webservice.client.Artist artist
    );
}
